## numpy module


'''Why use NumPy?

NumPy arrays are faster and more compact than Python lists. 
An array consumes less memory and is convenient to use.
NumPy uses much less memory to store data and it provides 
a mechanism of specifying the data types. 
This allows the code to be optimized even further.

array()    
linspace()   
logspace()   
arange()    
zeros()   
ones()    


'''

In [2]:
import numpy as np

In [103]:

### creating arrray using numpy ###

# list to array
simple_list = [6, 5, 3]
print(simple_list)
np.array(simple_list)
print(simple_list)


[6, 5, 3]
[6, 5, 3]


In [ ]:
# give array of 1 to 20 in sored form 
np.arange(20)


In [4]:
arr = np.array([1, 3, 6])
print(arr)

[1 3 6]


In [6]:
list_of_lists = [[1, 2, 6], [5, 7, 2], [7, 5, 0]]
np.array(list_of_lists)



array([[1, 2, 6],
       [5, 7, 2],
       [7, 5, 0]])

In [104]:

# a-range --->>> given range of function 
np.arange(5, 30)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
np.arange(5, 30, 4)


array([ 5,  9, 13, 17, 21, 25, 29])

In [11]:
# gives 100 zero of float data type by default
np.zeros(100)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 10 zeros of int daat type
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# ones matrix of 2x5
np.ones((2,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# linear space -->linspace
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
#  will reach 20 with 5 gaps inmiddle
np.linspace(0, 20, 7)


array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [19]:
# gives identity matrix of 10x10 of int daata typr
np.eye(10, dtype=int)


array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [20]:
# given randam matrix of 2x4 wiwth fload values(+ve values)
np.random.rand(2, 4)


array([[0.88788076, 0.0889047 , 0.02705273, 0.77387958],
       [0.66613681, 0.40941143, 0.13036737, 0.90139885]])

In [21]:
# given randam integer matrix of 2x4 with float values(+ve/-ve both values)

np.random.randn(2, 4)


array([[-0.2549545 ,  0.4946414 ,  0.72329833,  0.62909166],
       [ 0.47900858, -0.16935219,  0.22327487, -0.02823164]])

In [70]:
# gives random integer from selected range
np.random.randint(2, 10)


9

In [74]:
# in range of 2 to 100 4 random integer will be picked up
np.random.randint(2, 100, 4)


array([97, 12, 16, 69])

In [105]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [109]:
# storing sorted array in range 0 to 30
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [112]:
sample_array.reshape(5, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [126]:
rand_array = np.random.randint(3, 100, 20)
rand_array

array([71, 76,  4,  5, 54, 92, 76, 57, 52,  5, 40, 13, 92, 57, 65, 46, 63,
       83, 37, 41])

In [127]:
# gives minimum element from arr
rand_array.min()

4

In [129]:
# Gives index of minimum element
rand_array.argmin()


2

In [131]:
sample_array

sample_array.shape


(30,)

In [133]:
sample_array.reshape(5, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [134]:
# gives type of arr like int 32/64 string etc
sample_array.dtype


dtype('int32')

In [136]:
# eye is for identity matrix
a = np.eye(5)
a
# a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# ARRAY 1D

In [138]:
sample_array = np.arange(10, 21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [140]:

sample_array[8]


18

In [165]:

#  index --> 2 3 4
sample_array[2:5]


array([3, 4, 5])

In [169]:
sample_array+5
sample_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [147]:

sample_array[1:4] = 101
sample_array


array([1000101,     101,     101,     101, 1000101, 1000101, 1000101,
            17,      18,      19,      20])

In [144]:
subset_sample_Arrray = sample_array[0:7]
subset_sample_Arrray

array([ 10, 101, 101, 101,  14,  15,  16])

In [145]:

subset_sample_Arrray[:] = 1000101
subset_sample_Arrray


array([1000101, 1000101, 1000101, 1000101, 1000101, 1000101, 1000101])

In [149]:
sample_matrix = np.array(([50, 20, 1, 2], [20, 43, 2, 22], [44, 55, 66, 65]))
sample_matrix

array([[50, 20,  1,  2],
       [20, 43,  2, 22],
       [44, 55, 66, 65]])

In [150]:
sample_matrix[0][2]


1

In [151]:
sample_matrix[2]

array([44, 55, 66, 65])

In [154]:
sample_matrix[2, :]


array([44, 55, 66, 65])

In [155]:
sample_matrix[:, (3, 2)]

array([[ 2,  1],
       [22,  2],
       [65, 66]])

In [156]:
sample_array = np.arange(1, 31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [158]:
bool = sample_array < 10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [159]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
      ### Methods ####


# sample_array+sample_array
# np.exp(sample_array)
# np.sqrt(sample_array)
# np.log(sample_array)
# np.max(sample_array)
# np.min(sample_array)
# np.argmax(sample_array)
# np.argmin(sample_array)
# np.square(sample_array)
# np.std(sample_array)
# np.var(sample_array)
# np.mean(sample_array)

# array = np.random.randn(3, 6)
# array

# np.round(array, decimals=2)




In [4]:
sports = np.array(['golf', 'cricket', 'fball', 'cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [3]:
labels =['w','x','y','z']
sample_lists =[10,20,30,50]
array=np.array([1,2,3,8])
dict ={'w':10 ,'x': 20,'y': 30 ,'z':50}